FROM golang:1.25-alpine AS builder

WORKDIR /build

COPY . .

WORKDIR /build/Gateway

RUN go mod download

RUN go build -o main .

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /build/Gateway/main .

EXPOSE 8070

CMD ["./main"]
