version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_backend_blogs
    ports:
      - "8082:8082" 
    environment:
      - MONGO_URI=mongodb://mongo_blogs:27017
      - MONGO_DB=Blogs
      - MONGO_COLLECTION=Blogs
      - FOLLOWER_SERVICE_URL=http://follower_service:8083
    depends_on:
       mongo_blogs:
         condition: service_healthy
    networks:
      - blogs-net
      - follower-net 
  mongo_blogs:
    image: mongo:6
    container_name: mongo_blogs
    ports:
      - "27018:27017"
    volumes:
      - blog-mongo-data:/data/db
    networks:
      - blogs-net
    healthcheck:                    
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
networks:
  blogs-net:
  follower-net: 
    external: true
    name: follower_follower-net
volumes:
  blog-mongo-data: